version: '3.1'

networks:
  prober:
    driver: bridge

services:
  prober:
    image: sre-sla-prober
    build: .
    networks:
      - prober
    ports:
      - "8019:8080"
      - "8011:8085"
    environment:
      ONCALL_USERNAME: root
      ONCALL_PASSWORD: root
      ONCALL_URL: http://158.160.98.4:8080
      ONCALL_API_URL: http://158.160.98.4:8080/api/v0
